# Site settings
title: Nick Lashinsky's Online Presence 
email: lashinsky.nick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a blog from the trenches of product development, sales and startups in silicon valley
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nicklashinsky.com" # the base hostname & protocol for your site
twitter_username: lashinskynick
github_username:  nlashinsky

# Build settings
markdown: kramdown
